# Generated by Django 4.2.6 on 2023-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
